import subprocess
import os
import shutil
import re
from datetime import datetime
# Import player names from your config to ensure they match
try:
    from config import PLAYER_1_NAME, PLAYER_2_NAME
except ImportError:
    # Fallback if config.py isn't found or readable
    PLAYER_1_NAME = "A"
    PLAYER_2_NAME = "B"

# --- CONFIGURATION ---
NUM_BATTLES = 100           # How many matches to simulate
ENGINE_SCRIPT = "engine.py" # The name of your engine script
LOG_FILE = "gamelog.txt"    # The default log file generated by the engine
RESULTS_DIR = "simulation_results" # Directory to store individual battle logs

def parse_results(log_filename):
    """
    Parses the gamelog.txt to find the final bankrolls.
    Returns a dictionary with player names and their final scores.
    """
    p1_score = 0
    p2_score = 0
    
    try:
        with open(log_filename, 'r') as f:
            lines = f.readlines()
            
        # Look for the "Final" status line at the end of the log
        # Format usually looks like: "Final, A (-10), B (10)"
        final_line = None
        for line in reversed(lines):
            if line.startswith("Final"):
                final_line = line
                break
        
        if final_line:
            # Regex to extract Name and Score: e.g. ", A (-10)"
            # This regex looks for ", NAME (SCORE)" patterns
            matches = re.findall(r',\s*(\S+)\s*\((-?\d+)\)', final_line)
            for name, score in matches:
                if name == PLAYER_1_NAME:
                    p1_score = int(score)
                elif name == PLAYER_2_NAME:
                    p2_score = int(score)
                    
        return {PLAYER_1_NAME: p1_score, PLAYER_2_NAME: p2_score}

    except Exception as e:
        print(f"Error parsing log file: {e}")
        return {PLAYER_1_NAME: 0, PLAYER_2_NAME: 0}

def main():
    # Setup results directory
    if not os.path.exists(RESULTS_DIR):
        os.makedirs(RESULTS_DIR)
    else:
        # Optional: clear directory if you want fresh logs every time
        # shutil.rmtree(RESULTS_DIR)
        # os.makedirs(RESULTS_DIR)
        pass
    
    # Statistics Tracking
    p1_wins = 0
    p2_wins = 0
    ties = 0
    p1_total_bankroll = 0
    p2_total_bankroll = 0
    
    start_time = datetime.now()
    print(f"Starting simulation of {NUM_BATTLES} battles between {PLAYER_1_NAME} and {PLAYER_2_NAME}...")
    print("-" * 60)

    for i in range(1, NUM_BATTLES + 1):
        print(f"Running Battle {i}/{NUM_BATTLES}...", end="", flush=True)
        
        # Run the engine
        # We capture stdout/stderr to DEVNULL to avoid cluttering the console
        try:
            # Check if python3 or python is the correct command for your system
            subprocess.run(["python3", ENGINE_SCRIPT], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except (subprocess.CalledProcessError, FileNotFoundError):
            # Fallback to 'python' if 'python3' fails (common on Windows)
            try:
                subprocess.run(["python", ENGINE_SCRIPT], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            except subprocess.CalledProcessError:
                print(f" Error! Engine crashed in battle {i}.")
                continue

        # Parse results from the generated log file
        if not os.path.exists(LOG_FILE):
            print(f" Error! {LOG_FILE} not found.")
            continue

        results = parse_results(LOG_FILE)
        p1_score = results.get(PLAYER_1_NAME, 0)
        p2_score = results.get(PLAYER_2_NAME, 0)
        
        # Update Stats
        p1_total_bankroll += p1_score
        p2_total_bankroll += p2_score
        
        winner = "Tie"
        if p1_score > p2_score:
            p1_wins += 1
            winner = PLAYER_1_NAME
        elif p2_score > p1_score:
            p2_wins += 1
            winner = PLAYER_2_NAME
        else:
            ties += 1

        print(f" Winner: {winner} ({p1_score} vs {p2_score})")

        # Save log file for this battle so you can inspect it later
        # Renames 'gamelog.txt' to 'simulation_results/battle_X.txt'
        shutil.copy(LOG_FILE, os.path.join(RESULTS_DIR, f"battle_{i}.txt"))

    # --- FINAL REPORT ---
    elapsed_time = datetime.now() - start_time
    print("\n" + "=" * 60)
    print(f"SIMULATION COMPLETE")
    print("=" * 60)
    print(f"Total Battles: {NUM_BATTLES}")
    print(f"Time Elapsed:  {elapsed_time}")
    print("-" * 60)
    print(f"{PLAYER_1_NAME} Wins: {p1_wins} ({p1_wins/NUM_BATTLES:.1%})")
    print(f"{PLAYER_2_NAME} Wins: {p2_wins} ({p2_wins/NUM_BATTLES:.1%})")
    print(f"Ties:    {ties} ({ties/NUM_BATTLES:.1%})")
    print("-" * 60)
    print(f"Avg Bankroll {PLAYER_1_NAME}: {p1_total_bankroll / NUM_BATTLES:.2f}")
    print(f"Avg Bankroll {PLAYER_2_NAME}: {p2_total_bankroll / NUM_BATTLES:.2f}")
    print("=" * 60)
    print(f"Detailed logs saved in '{RESULTS_DIR}/'")

if __name__ == "__main__":
    main()